name: yalla-habibi-project

services:
  #Database server
  postgres:
    image: "postgres:17.5-alpine3.21"
    hostname: postgres
    environment:
      POSTGRES_USER_FILE: /run/secrets/pg_user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_pw
      TZ: America/Chicago
      PGTZ: America/Chicago
    secrets:
      - pg_user
      - pg_pw
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/logs:/var/log/postgresql
    command: >
      postgres -c log_directory=/var/log/postgresql
               -c log_filename=postgresql.log
               -c log_statement=all
               -c log_connections=on
               -c log_disconnections=on
               -c log_destination=stderr,csvlog
               -c log_rotation_age=1d
               -c shared_preload_libraries=pg_stat_statements
               -c pg_stat_statements.track=all
    restart: unless-stopped
    shm_size: 256mb
    ports:
      - "5555:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres", "-U", "banana_admin"]
      interval: 120s
      timeout: 60s
      retries: 5
      start_period: 30s

  #FASTAPI server
  backend:
    build: .
    environment:
      POSTGRES_USER_FILE: /run/secrets/pg_user
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_pw
      DB_NAME: postgres
      DB_DRIVER: postgresql
    stop_signal: SIGINT
    volumes:
      - ./backend:/code/app
    ports:
      - "8000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/bin/ash","-c"]
    command:
      - |
        fastapi run app/main.py --port 5000 --reload
    secrets:
      - pg_user
      - pg_pw

  #Web/proxy server
  web:
    image: "nginx:1.28.0-alpine3.21"
    environment:
      - API_SERVER_ADDR=backend:5000
    command: /bin/ash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - ./frontend/web:/var/web
      - ./config/nginx/nginx.conf:/tmp/nginx.conf
    restart: unless-stopped
    ports:
      - "8777:8777"
    depends_on:
      - backend

#Secrets for passwords/user accounts
secrets:
  pg_user:
    file: ./secrets/pg_user.txt
  pg_pw:
    file: ./secrets/pg_pw.txt
